version: '3.8'

services:
  python_scrapper_ms:
    build: 
      context: docker-services/substack-post-scrapper
      dockerfile: Dockerfile
    image: python_scrapper_ms
    volumes:
      - ${LOCAL_DATA_FOLDER_PATH}:/app/data
      - ${MARKDOWN_FILES_FOLDER_PATH}:${CONTAINER_MARKDOWN_FILES_FOLDER_PATH}
    ports:
      - "${PORT_MS1}:3010"
    environment:
      - CONTAINER_MARKDOWN_FILES_FOLDER_PATH=${CONTAINER_MARKDOWN_FILES_FOLDER_PATH}

  mail-aggregator-api:
    build:
      context: docker-services/api
      dockerfile: Dockerfile
    image: mail-aggregator-api
    volumes:
      - ${LOCAL_DATA_FOLDER_PATH}:/app/data
    ports:
      - "${PORT_API}:3000"
    environment:
      - PORT=${PORT_API}
      - CONTAINER_CATEGORIES_FILE_PATH=${CONTAINER_CATEGORIES_FILE_PATH}
      - MS1_URL=${MS1_URL}
    depends_on:
      - python_scrapper_ms
